import mongoose from "mongoose";

/**
 * ResetToken — stores predictable password-reset tokens.
 *
 * VULNERABILITY (A06 — Insecure Design, CWE-330):
 * Tokens are short 4-digit sequential integers generated by incrementing
 * a global counter. They are NOT cryptographically random. Combined with
 * zero rate-limiting on the verify endpoint, an attacker can brute-force
 * the entire 0000–9999 space in seconds with a simple script.
 *
 * Fix: use crypto.randomBytes(32).toString('hex') and enforce rate-limiting.
 */
const resetTokenSchema = new mongoose.Schema({
  email: {
    type: String,
    required: true,
  },
  token: {
    type: Number, // short sequential integer — intentionally weak
    required: true,
  },
  createdAt: {
    type: Date,
    default: Date.now,
    // Tokens expire after 15 minutes (still brute-forceable in that window)
    expires: 900,
  },
});

const ResetToken = mongoose.model("ResetToken", resetTokenSchema);
export default ResetToken;
